--------------------------------------------------------
--  File created - miercuri-aprilie-12-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REGIMURI
--------------------------------------------------------
  drop table regimuri cascade constraints purge;
  CREATE TABLE "REGIMURI" 
   (	"ID_REGIM" NUMBER(10,0), 
	"PROPRIETATE_REGIM" VARCHAR2(200 BYTE), 
	"VIZITABIL" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLICATIE" ;
REM INSERTING into REGIMURI
SET DEFINE OFF;
Insert into REGIMURI (ID_REGIM,PROPRIETATE_REGIM,VIZITABIL) values ('600','maxima siguranta','1');
Insert into REGIMURI (ID_REGIM,PROPRIETATE_REGIM,VIZITABIL) values ('601','liber','1');
Insert into REGIMURI (ID_REGIM,PROPRIETATE_REGIM,VIZITABIL) values ('602','restrictiv','1');
Insert into REGIMURI (ID_REGIM,PROPRIETATE_REGIM,VIZITABIL) values ('603','semi-inchis','1');
Insert into REGIMURI (ID_REGIM,PROPRIETATE_REGIM,VIZITABIL) values ('604','inchis','0');
--------------------------------------------------------
--  DDL for Index REGIM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REGIM_PK" ON "REGIMURI" ("ID_REGIM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLICATIE" ;
--------------------------------------------------------
--  Constraints for Table REGIMURI
--------------------------------------------------------

  ALTER TABLE "REGIMURI" ADD CONSTRAINT "REGIM_PK" PRIMARY KEY ("ID_REGIM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLICATIE"  ENABLE;
